"""Python access to the packaged native ``mlx-guard`` supervisor."""

from importlib.metadata import version

from ._binary import (
    BinaryDiscoveryError,
    BinaryVersionError,
    PackageIntegrityError,
    binary_path,
    binary_version,
)
from ._checkpoint import (
    CheckpointArtifact,
    CheckpointArtifactKind,
    CheckpointCallbackError,
    CheckpointError,
    CheckpointProtocolError,
    CheckpointRequest,
    CheckpointResponse,
    CheckpointWorker,
)
from ._client import (
    ConfigurationError,
    GuardError,
    GuardProcess,
    InvalidReportError,
    MissingReportError,
    ObserveConfig,
    Outcome,
    OutcomeKind,
    OutputEvent,
    OutputStream,
    Report,
    ReportError,
    ResultMismatchError,
    RunConfig,
    RunResult,
    SupervisorDiscoveryError,
    SupervisorStartError,
    load_report,
    run,
    start,
    supervisor_argv,
)

__version__ = version("mlx-guard")

__all__ = [
    "BinaryDiscoveryError",
    "BinaryVersionError",
    "CheckpointArtifact",
    "CheckpointArtifactKind",
    "CheckpointCallbackError",
    "CheckpointError",
    "CheckpointProtocolError",
    "CheckpointRequest",
    "CheckpointResponse",
    "CheckpointWorker",
    "ConfigurationError",
    "GuardError",
    "GuardProcess",
    "InvalidReportError",
    "MissingReportError",
    "ObserveConfig",
    "Outcome",
    "OutcomeKind",
    "OutputEvent",
    "OutputStream",
    "PackageIntegrityError",
    "Report",
    "ReportError",
    "ResultMismatchError",
    "RunConfig",
    "RunResult",
    "SupervisorDiscoveryError",
    "SupervisorStartError",
    "__version__",
    "binary_path",
    "binary_version",
    "load_report",
    "run",
    "start",
    "supervisor_argv",
]
